### ISSUE TITLE
basic questions

### ISSUE THREAD

**Issue by Livy13** [mcteamtls/gabet#1]
Ah... so kann man also kein Dokument hinzufügen. Dann eben so...
Ich sammle hier mal ein paar Fragen zur Story, die sich mir auftun, während ich hier herumstöbere.

**Comment by maxlxl** [comment]
Ok, Ich werde versuchen, sie zu beantworten :D

**Comment by maxlxl** [comment]
Ach ja, du hast oben hinter den Namen ein kleines +, mit dem solltest du neue Dateien und Ordner erstellen können :D

**Comment by Livy13** [comment]
1. Spielt das jeder für sich allein? Also ohne andere Spieler zu sehen oder mit ihnen zu interagieren? Das was an Story bereits besteht lässt darauf schließen
2. kann man diesen Post hier irgendwie löschen? ich hätte gern ein dokument dafür...

**Comment by Livy13** [comment]
das hier hab ich bei dem plus gemacht...aber da kann ich nur selbst solche verzeichnisdinger erstellen... na erstmal egal... ich schau mich mal genauer auf gabet um...

**Comment by maxlxl** [comment]
1. Für den Anfang war das so geplant, später soll es quests geben, die man nur im Multiplayer lösen kann.
2. Schon geschehen: https://github.com/mcteamtls/gabet/blob/master/intern/Basic%20Question.md
